name: Build Linux
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm install -g @quasar/cli
      - run: quasar build --mode electron
      - uses: actions/upload-artifact@v4
        with:
          name: grapetool_linux
          path: /home/runner/work/grapetool_v2/grapetool_v2/dist/electron/Packaged/grapetool-linux-x64
      - run: echo "🍏 This job's status is ${{ job.status }}."
